### ISSUE TITLE
shrink navbar to less entries

### ISSUE THREAD

**Issue by torbjoernk** [Parallel-in-Time/parallel-in-time.github.io#39]
The high number of navbar entries account for broken layout on some screen sizes. We should come up with another grouping.

Suggestion:

- Workshops
  - Upcoming
  - Past
  - Bylaws
- News
- Research
  - Methods
  - Codes
  - References
- People
  - Groups
  - Projects
- About

Opinions? Suggestions?

**Comment by danielru** [comment]
Hm, I'd rather have Projects as part of Research - but then Groups is alone in People. What about

- News (first entry)
- Workshops
  - Upcoming
  - Past
  - Bylaws
- Research
  - Methods
  - Codes
  - Groups
  - Projects
- References (probably leave this at top level, because I think it might get used a lot?)
- About

**Comment by danielru** [comment]
Closed by #40
